version: '3.2'

services:
  db:
    image: mongo
    restart: unless-stopped
    volumes:
      - picturebea_db:/data/db

  backend:
    build: backend/
    restart: unless-stopped
    depends_on: 
      - db
    env_file: .env

  frontend:
    build: frontend/
    restart: unless-stopped
    ports:
      - 8087:80

volumes:
  picturebea_db: